//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.09.18 at 09:31:44 PM BST
//


package nl.adaptivity.process.processmodel.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.adaptivity.process.processmodel.jaxb package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
@SuppressWarnings("static-method")
public class ObjectFactory {

    private final static QName _ProcessModel_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "processModel");
    private final static QName _JoinPredecessor_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "predecessor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.adaptivity.process.processmodel.jaxb
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TProcessModel }
     *
     */
    public TProcessModel createTProcessModel() {
        return new TProcessModel();
    }

    /**
     * Create an instance of {@link StartNode }
     *
     */
    public StartNode createStartNode() {
        return new StartNode();
    }

    /**
     * Create an instance of {@link Activity }
     *
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link ImportType }
     *
     */
    public ImportType createImportType() {
        return new ImportType();
    }

    /**
     * Create an instance of {@link Message }
     *
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ExportType }
     *
     */
    public ExportType createExportType() {
        return new ExportType();
    }

    /**
     * Create an instance of {@link EndNode }
     *
     */
    public EndNode createEndNode() {
        return new EndNode();
    }

    /**
     * Create an instance of {@link Join }
     *
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link MessageType }
     *
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcessModel }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "processModel")
    public JAXBElement<TProcessModel> createProcessModel(TProcessModel value) {
        return new JAXBElement<TProcessModel>(_ProcessModel_QNAME, TProcessModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "predecessor", scope = Join.class)
    @XmlIDREF
    public JAXBElement<Object> createJoinPredecessor(Object value) {
        return new JAXBElement<Object>(_JoinPredecessor_QNAME, Object.class, Join.class, value);
    }

}
