//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.27 at 08:15:55 PM CEST 
//


package nl.adaptivity.process.processmodel.jaxb;

import java.util.*;

import javax.xml.bind.annotation.*;


/**
 * <p>
 * Java class for Activity complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Activity&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://adaptivity.nl/ProcessEngine/}ProcessModelNode&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;element name=&quot;import&quot; type=&quot;{http://adaptivity.nl/ProcessEngine/}ImportType&quot;/&gt;
 *           &lt;element name=&quot;export&quot; type=&quot;{http://adaptivity.nl/ProcessEngine/}ExportType&quot;/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name=&quot;message&quot; type=&quot;{http://adaptivity.nl/ProcessEngine/}Message&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;predecessor&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlRootElement(name = "activity")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Activity", propOrder = { "imports", "exports", "message", "condition" })
public final class XmlActivity extends XmlProcessModelNode {

  
  @XmlElement(name = "export")
  protected List<XmlExportType> exports;
  
  @XmlElement(name = "import")
  protected List<XmlImportType> imports;

  @XmlElement(required = true)
  protected XmlMessage message;

  @XmlAttribute(required = true)
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected XmlProcessModelNode predecessor;

  @XmlAttribute
  protected String name;
  
  @XmlElement
  private String condition;

  /**
   * Gets the value of the importOrExport property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the importOrExport property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getImportOrExport().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link XmlExportType } {@link XmlImportType }
   */
  public List<XmlImportType> getImports() {
    if (imports == null) {
      imports = new ArrayList<XmlImportType>();
    }
    return this.imports;
  }

  public List<XmlExportType> getExports() {
    if (exports == null) {
      exports = new ArrayList<XmlExportType>();
    }
    return this.exports;
  }

  /**
   * Gets the value of the message property.
   * 
   * @return possible object is {@link XmlMessage }
   */
  public XmlMessage getXmlMessage() {
    return message;
  }

  /**
   * Sets the value of the message property.
   * 
   * @param value allowed object is {@link XmlMessage }
   */
  public void setXmlMessage(XmlMessage value) {
    this.message = value;
  }

  /**
   * Gets the value of the predecessor property.
   * 
   * @return possible object is {@link Object }
   */
  public XmlProcessModelNode getPredecessor() {
    return predecessor;
  }

  /**
   * Sets the value of the predecessor property.
   * 
   * @param value allowed object is {@link Object }
   */
  public void setPredecessor(XmlProcessModelNode value) {
    this.predecessor = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  @Override
  public Collection<XmlProcessModelNode> getPredecessors() {
    return Arrays.asList(predecessor);
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public String getCondition() {
    return condition;
  }

}
