//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.27 at 08:15:55 PM CEST 
//


package nl.adaptivity.process.processmodel.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import nl.adaptivity.process.engine.processModel.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.adaptivity.process.processmodel.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class XmlObjectFactory {

    private final static QName _Activity_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "activity");
    private final static QName _End_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "end");
    private final static QName _Join_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "join");
    private final static QName _Start_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "start");
    private final static QName _ProcessModel_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "processModel");
    private final static QName _JoinPredecessor_QNAME = new QName("http://adaptivity.nl/ProcessEngine/", "predecessor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.adaptivity.process.processmodel.jaxb
     * 
     */
    public XmlObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlMessage }
     * 
     */
    public XmlMessage createXmlMessage() {
        return new XmlMessage();
    }

    /**
     * Create an instance of {@link XmlActivity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link XmlJoin }
     * 
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link XmlProcessModel }
     * 
     */
    public XmlProcessModel createXmlProcessModel() {
        return new XmlProcessModel();
    }

    /**
     * Create an instance of {@link XmlExportType }
     * 
     */
    public XmlExportType createXmlExportType() {
        return new XmlExportType();
    }

    /**
     * Create an instance of {@link XmlMessageType }
     * 
     */
    public XmlMessageType createXmlMessageType() {
        return new XmlMessageType();
    }

    /**
     * Create an instance of {@link XmlEndNode }
     * 
     */
    public EndNode createEndNode() {
        return new EndNode();
    }

    /**
     * Create an instance of {@link XmlImportType }
     * 
     */
    public XmlImportType createXmlImportType() {
        return new XmlImportType();
    }

    /**
     * Create an instance of {@link XmlStartNode }
     * 
     */
    public StartNode createStartNode() {
        return new StartNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlActivity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "activity")
    public JAXBElement<Activity> createActivity(Activity value) {
        return new JAXBElement<Activity>(_Activity_QNAME, Activity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlEndNode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "end")
    public JAXBElement<EndNode> createEnd(EndNode value) {
        return new JAXBElement<EndNode>(_End_QNAME, EndNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlJoin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "join")
    public JAXBElement<Join> createJoin(Join value) {
        return new JAXBElement<Join>(_Join_QNAME, Join.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlStartNode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "start")
    public JAXBElement<StartNode> createStart(StartNode value) {
        return new JAXBElement<StartNode>(_Start_QNAME, StartNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlProcessModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "processModel")
    public JAXBElement<XmlProcessModel> createProcessModel(XmlProcessModel value) {
        return new JAXBElement<XmlProcessModel>(_ProcessModel_QNAME, XmlProcessModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adaptivity.nl/ProcessEngine/", name = "predecessor", scope = Join.class)
    @XmlIDREF
    public JAXBElement<ProcessNode> createJoinPredecessor(ProcessNode value) {
        return new JAXBElement<ProcessNode>(_JoinPredecessor_QNAME, ProcessNode.class, Join.class, value);
    }

}
