//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.27 at 08:15:55 PM CEST 
//


package nl.adaptivity.process.processmodel.jaxb;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.xml.bind.annotation.*;


/**
 * <p>
 * Java class for StartNode complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;StartNode&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://adaptivity.nl/ProcessEngine/}ProcessModelNode&quot;&gt;
 *       &lt;choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *         &lt;element name=&quot;import&quot; type=&quot;{http://adaptivity.nl/ProcessEngine/}ImportType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/choice&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlRootElement(name = "start")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartNode", propOrder = { "_import" })
public final class XmlStartNode extends XmlProcessModelNode {

  @XmlElement(name = "import")
  protected List<XmlImportType> _import;

  /**
   * Gets the value of the import property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the import property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getImport().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link XmlImportType }
   */
  public List<XmlImportType> getImport() {
    if (_import == null) {
      _import = new ArrayList<XmlImportType>();
    }
    return this._import;
  }

  @Override
  public Collection<XmlProcessModelNode> getPredecessors() {
    return new ArrayList<XmlProcessModelNode>(0);
  }

}
