//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.24 at 08:12:58 PM CEST
//


package org.w3.soapEnvelope;

import net.devrieze.util.StringUtil;
import nl.adaptivity.util.xml.*;
import nl.adaptivity.xml.XmlException;
import nl.adaptivity.xml.XmlReader;
import nl.adaptivity.xml.XmlWriter;
import org.jetbrains.annotations.NotNull;

import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;


/**
 * <p>
 * Java class for Envelope complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Envelope">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2003/05/soap-envelope}Header" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2003/05/soap-envelope}Body"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = Envelope.ELEMENTLOCALNAME, propOrder = { "header", "body" })
@XmlRootElement(name = Envelope.ELEMENTLOCALNAME, namespace = Envelope.NAMESPACE)
@XmlDeserializer(Envelope.Factory.class)
public class Envelope implements SimpleXmlDeserializable, XmlSerializable{

  public static class Factory implements XmlDeserializerFactory<Envelope> {

    @Override
    public Envelope deserialize(final XmlReader in) throws XmlException {
      return Envelope.deserialize(in);
    }
  }

  public static final String NAMESPACE = "http://www.w3.org/2003/05/soap-envelope";

  public static final String ELEMENTLOCALNAME = "Envelope";

  public static final String PREFIX = "env";

  public static final QName ELEMENTNAME = new QName(NAMESPACE, ELEMENTLOCALNAME, PREFIX);

  public static final String MIMETYPE = "application/soap+xml";

  @XmlElement(name = Header.ELEMENTLOCALNAME)
  protected Header header;

  @XmlElement(name = Body.ELEMENTLOCALNAME, required = true)
  protected Body body;

  @XmlAnyAttribute
  private final Map<QName, String> otherAttributes = new HashMap<>();

  private URI encodingStyle;

  public static Envelope deserialize(final XmlReader in) throws XmlException {
    return XmlUtil.deserializeHelper(new Envelope(), in);
  }

  @Override
  public QName getElementName() {
    return ELEMENTNAME;
  }

  @Override
  public void onBeforeDeserializeChildren(final XmlReader in) throws XmlException {
    // ignore
  }

  @Override
  public boolean deserializeAttribute(final CharSequence attributeNamespace, final CharSequence attributeLocalName, final CharSequence attributeValue) {
    if (StringUtil.isEqual("encodingStyle", attributeLocalName)) {
      setEncodingStyle(URI.create(StringUtil.toString(attributeValue)));
      return true;
    }
    QName qname = new QName(StringUtil.toString(attributeNamespace), StringUtil.toString(attributeLocalName));
    otherAttributes.put(qname, StringUtil.toString(attributeValue));
    return true;
  }

  @Override
  public boolean deserializeChildText(final CharSequence elementText) {
    return false;
  }

  @Override
  public boolean deserializeChild(final XmlReader in) throws XmlException {
    if (StringUtil.isEqual(NAMESPACE,in.getNamespaceUri())) {
      if (StringUtil.isEqual(Header.ELEMENTLOCALNAME, in.getLocalName())) {
        setHeader(Header.deserialize(in));
        return true;
      } else if (StringUtil.isEqual(Body.ELEMENTLOCALNAME, in.getLocalName())) {
        setBody(Body.deserialize(in));
        return true;
      }
    }
    return false;
  }

  @Override
  public void serialize(final XmlWriter out) throws XmlException {
    XmlUtil.writeStartElement(out, getElementName());
    XmlUtil.writeAttribute(out, "encodingStyle", encodingStyle.toString());
    for(Entry<QName, String> attr:otherAttributes.entrySet()) {
      XmlUtil.writeAttribute(out, attr.getKey(), attr.getValue());
    }
    XmlUtil.writeChild(out, header);
    XmlUtil.writeChild(out, body);
    XmlUtil.writeEndElement(out, getElementName());
  }

  /**
   * Gets the value of the header property.
   *
   * @return possible object is {@link Header }
   */
  public Header getHeader() {
    return header;
  }

  /**
   * Sets the value of the header property.
   *
   * @param value allowed object is {@link Header }
   */
  public void setHeader(final Header value) {
    this.header = value;
  }

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link Body }
   */
  public Body getBody() {
    return body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link Body }
   */
  public void setBody(final Body value) {
    this.body = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property
   * on this class.
   * <p>
   * the map is keyed by the name of the attribute and the value is the string
   * value of the attribute. the map returned by this method is live, and you
   * can add new attribute by updating the map directly. Because of this design,
   * there's no setter.
   *
   * @return always non-null
   */
  @NotNull
  public Map<QName, String> getOtherAttributes() {
    return otherAttributes;
  }

  @XmlAttribute(name = "encodingStyle")
  public URI getEncodingStyle() {
    return encodingStyle;
  }

  public void setEncodingStyle(final URI encodingStyle) {
    this.encodingStyle = encodingStyle;
  }

}
