/*
 * Copyright (c) 2016.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with Foobar.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.24 at 08:12:58 PM CEST
//


package org.w3.soapEnvelope;

import nl.adaptivity.xml.schema.annotations.Child;
import nl.adaptivity.xml.schema.annotations.Element;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for faultreason complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="faultreason">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Text" type="{http://www.w3.org/2003/05/soap-envelope}reasontext" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Element(name="Reason",
         nsUri = Envelope.NAMESPACE,
         nsPrefix = Envelope.NAMESPACE,
         children = {@Child(name="Text", type=Reasontext.class)})
public class Faultreason {

  protected List<Reasontext> text;

  /**
   * Gets the value of the text property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the text property.
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getText().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Reasontext }
   */
  public List<Reasontext> getText() {
    if (text == null) {
      text = new ArrayList<>();
    }
    return this.text;
  }

}
