/*
 * Copyright (c) 2016.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with Foobar.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.24 at 08:12:58 PM CEST 
//


package org.w3.soapEnvelope;

import nl.adaptivity.xml.schema.annotations.Child;
import nl.adaptivity.xml.schema.annotations.Element;
import nl.adaptivity.xml.schema.annotations.XmlName;

import javax.xml.namespace.QName;


/**
 * <p>
 * Java class for faultcode complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="faultcode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Value" type="{http://www.w3.org/2003/05/soap-envelope}faultcodeEnum"/>
 *         &lt;element name="Subcode" type="{http://www.w3.org/2003/05/soap-envelope}subcode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Element(name="Code",
         nsUri = Envelope.NAMESPACE,
         nsPrefix = Envelope.PREFIX,
         children = {
              @Child(name="Value", type=QName.class),
              @Child(name="Subcode", type=Subcode.class)
         })
public class Faultcode {

  protected QName value;

  protected Subcode subcode;

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link QName }
   */
  @XmlName("Value")
  public QName getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link QName }
   */
  public void setValue(final QName value) {
    this.value = value;
  }

  /**
   * Gets the value of the subcode property.
   * 
   * @return possible object is {@link Subcode }
   */
  @XmlName("Subcode")
  public Subcode getSubcode() {
    return subcode;
  }

  /**
   * Sets the value of the subcode property.
   * 
   * @param value allowed object is {@link Subcode }
   */
  public void setSubcode(final Subcode value) {
    this.subcode = value;
  }

}
