/*
 * Copyright (c) 2016.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with Foobar.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.24 at 08:12:58 PM CEST
//


package org.w3.soapEnvelope;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.w3.soapEnvelope package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Envelope_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Envelope");

  private final static QName _Upgrade_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Upgrade");

  private final static QName _Header_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Header");

  private final static QName _Body_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Body");

  private final static QName _NotUnderstood_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "NotUnderstood");

  private final static QName _Fault_QNAME = new QName("http://www.w3.org/2003/05/soap-envelope", "Fault");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: org.w3.soapEnvelope
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link Reasontext }
   */
  @NotNull
  public Reasontext createReasontext() {
    return new Reasontext();
  }

  /**
   * Create an instance of {@link Faultreason }
   */
  @NotNull
  public Faultreason createFaultreason() {
    return new Faultreason();
  }

  /**
   * Create an instance of {@link Faultcode }
   */
  @NotNull
  public Faultcode createFaultcode() {
    return new Faultcode();
  }

  /**
   * Create an instance of {@link Fault }
   */
  @NotNull
  public Fault createFault() {
    return new Fault();
  }

  /**
   * Create an instance of {@link Detail }
   */
  @NotNull
  public Detail createDetail() {
    return new Detail();
  }

  /**
   * Create an instance of {@link SupportedEnvType }
   */
  @NotNull
  public SupportedEnvType createSupportedEnvType() {
    return new SupportedEnvType();
  }

  /**
   * Create an instance of {@link Body }
   */
  @NotNull
  public Body createBody() {
    return new Body();
  }

  /**
   * Create an instance of {@link Subcode }
   */
  @NotNull
  public Subcode createSubcode() {
    return new Subcode();
  }

  /**
   * Create an instance of {@link Header }
   */
  @NotNull
  public Header createHeader() {
    return new Header();
  }

  /**
   * Create an instance of {@link Envelope }
   */
  @NotNull
  public Envelope createEnvelope() {
    return new Envelope();
  }

  /**
   * Create an instance of {@link UpgradeType }
   */
  @NotNull
  public UpgradeType createUpgradeType() {
    return new UpgradeType();
  }

  /**
   * Create an instance of {@link NotUnderstoodType }
   */
  @NotNull
  public NotUnderstoodType createNotUnderstoodType() {
    return new NotUnderstoodType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Envelope }{@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "Envelope")
  public JAXBElement<Envelope> createEnvelope(final Envelope value) {
    return new JAXBElement<>(_Envelope_QNAME, Envelope.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link UpgradeType }
   * {@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "Upgrade")
  public JAXBElement<UpgradeType> createUpgrade(final UpgradeType value) {
    return new JAXBElement<>(_Upgrade_QNAME, UpgradeType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Header }{@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "Header")
  public JAXBElement<Header> createHeader(final Header value) {
    return new JAXBElement<>(_Header_QNAME, Header.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Body }{@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "Body")
  public JAXBElement<Body> createBody(final Body value) {
    return new JAXBElement<>(_Body_QNAME, Body.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link NotUnderstoodType }
   * {@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "NotUnderstood")
  public JAXBElement<NotUnderstoodType> createNotUnderstood(final NotUnderstoodType value) {
    return new JAXBElement<>(_NotUnderstood_QNAME, NotUnderstoodType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
   */
  @Nullable
  @XmlElementDecl(namespace = "http://www.w3.org/2003/05/soap-envelope", name = "Fault")
  public JAXBElement<Fault> createFault(final Fault value) {
    return new JAXBElement<>(_Fault_QNAME, Fault.class, null, value);
  }

}
