version: 2
updates:
  - package-ecosystem: "gradle"
    update-types:
      - "minor"
      - "patch"
  - package-ecosystem: "npm"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "yarn"
    ignore:
      - dependency-name: "*"
