version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      update-types:
        - "version-update:semver-major"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: yearly
    ignore:
      - dependency-name: "*"

