//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.27 at 08:15:55 PM CEST
//


package nl.adaptivity.process.processModel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * May contain literal elements as content. In that case only the paramName
 * attribute is used.
 * <p>
 * Java class for ExportType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ExportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="node" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="paramName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportType", propOrder = { "content" })
public class XmlExportType implements IXmlExportType {

  public static final String ELEMENTNAME = "export";

  @XmlMixed
  @XmlAnyElement(lax = true)
  protected List<Object> content;

  @XmlAttribute
  protected String node;

  @XmlAttribute
  protected String name;

  @XmlAttribute(required = true)
  protected String paramName;

  @XmlAttribute
  protected String path;

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#getContent()
   */
  @Override
  public List<Object> getContent() {
    if (content == null) {
      content = new ArrayList<>();
    }
    return this.content;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#getNode()
   */
  @Override
  public String getNode() {
    return node;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#setNode(java.lang.String)
   */
  @Override
  public void setNode(final String value) {
    this.node = value;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#getName()
   */
  @Override
  public String getName() {
    return name;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#setName(java.lang.String)
   */
  @Override
  public void setName(final String value) {
    this.name = value;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#getParamName()
   */
  @Override
  public String getParamName() {
    return paramName;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#setParamName(java.lang.String)
   */
  @Override
  public void setParamName(final String value) {
    this.paramName = value;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#getPath()
   */
  @Override
  public String getPath() {
    return path;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.XmlImportType#setPath(java.lang.String)
   */
  @Override
  public void setPath(final String value) {
    this.path = value;
  }

  public static XmlExportType get(IXmlExportType pExport) {
    if (pExport instanceof XmlExportType) { return (XmlExportType) pExport; }
    XmlExportType result = new XmlExportType();
    result.content = pExport.getContent();
    result.name = pExport.getName();
    result.node = pExport.getNode();
    result.paramName = pExport.getParamName();
    result.path = pExport.getPath();
    return result;
  }

}
