//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.27 at 08:15:55 PM CEST
//


package nl.adaptivity.process.processModel;

import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.DocumentFragment;
import org.w3c.dom.Element;
import org.w3c.dom.Node;


/**
 * <p>Java class for Message complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="service" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="endpoint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "Message")
public class XmlMessage {

    @XmlAttribute(required = true)
    protected QName service;
    @XmlAttribute(required = true)
    protected String endpoint;
    @XmlAttribute(required = true)
    protected QName operation;
    private Node aBody;
    private ArrayList<Object> aAny;

    /**
     * Gets the value of the service property.
     *
     * @return
     *     possible object is
     *     {@link QName }
     *
     */
    public QName getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     *
     * @param value
     *     allowed object is
     *     {@link QName }
     *
     */
    public void setService(QName value) {
        this.service = value;
    }

    /**
     * Gets the value of the endpoint property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEndpoint(String value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the operation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public QName getOperation() {
        return operation;
    }

    @XmlAnyElement(lax=false)
    public Collection<Object> getAny() {
      if (aAny == null) {
        aAny = new ArrayList<Object>(1);
        if (aBody!=null) {
          aAny.add(aBody);
          aBody = null;
        }
      }
      return aAny;
    }

    public Node getMessageBody() {
      if (aBody ==null && aAny!=null) {
        Iterator<Object> it = aAny.iterator();
        while(it.hasNext()) {
          Object next = it.next();
          if ((next instanceof Element) || (next instanceof Document) || (next instanceof DocumentFragment)) {
            if (aBody !=null) {
              throw new IllegalStateException("Only one member allowed");
            }
            aBody = (Node) next;
          }
        }
        if (aBody!=null) {
          aAny = null;
        }
      }

      return aBody;
    }

    public void setMessageBody(Object o) {
      if (o instanceof Node) {
        aBody = (Node) o;
      }
    }

    /**
     * Sets the value of the operation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOperation(QName value) {
        this.operation = value;
    }

    public Source getBodySource() {
      return new DOMSource(getMessageBody());
    }

    @Override
    public String toString() {
      TransformerFactory tf = TransformerFactory.newInstance();
      Transformer t;
      try {
        t = tf.newTransformer();
      } catch (TransformerConfigurationException e) {
        return super.toString();
      }
      StringWriter sw = new StringWriter();
      StreamResult sr = new StreamResult(sw);
      try {
        t.transform(getBodySource(), sr);
      } catch (TransformerException e) {
        return super.toString();
      }
      return sw.toString();
    }
}
