//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.27 at 08:15:55 PM CEST
//


package nl.adaptivity.process.processModel;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;

import nl.adaptivity.process.processModel.XmlResultType.Adapter;
import nl.adaptivity.util.xml.XmlUtil;
import org.w3c.dom.Node;

import nl.adaptivity.process.engine.PETransformer;
import nl.adaptivity.process.engine.ProcessData;


/**
 * <p>
 * Java class for ImportType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ImportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
//@XmlAccessorType(XmlAccessType.NONE)
//@XmlType(name = "ResultType")
@XmlJavaTypeAdapter(Adapter.class)
public class XmlResultType extends XPathHolder implements IXmlResultType {

  @XmlRootElement(name=XmlResultType.ELEMENTNAME)
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "ResultType", propOrder = { "content" })
  static class AdaptedResult {
    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> content = new ArrayList<>();

    @XmlAttribute(name="name", required = true)
    protected String name;

    @XmlAttribute
    protected String path;

  }

  static class Adapter extends XmlAdapter<AdaptedResult, XmlResultType> {

    @Override
    public XmlResultType unmarshal(final AdaptedResult v) throws Exception {
      ArrayList<Object> newContent = new ArrayList<>(v.content.size());
      for(Object o: v.content) {
        if (o instanceof Node) {
          try {
            newContent.add(XmlUtil.cannonicallize((Node) o));
          } catch (Exception e) {
            Logger.getAnonymousLogger().log(Level.WARNING, "Failure to cannonicalize node", e);
            newContent.add(o);
          }
        } else if(o instanceof CharSequence) {
          CharSequence s = (CharSequence) o;
          if (! XmlUtil.isXmlWhitespace(s)) {
            newContent.add(o);
          }
        } else {
          newContent.add(o);
        }
      }
      return new XmlResultType(v.name, v.path, newContent);
    }

    @Override
    public AdaptedResult marshal(final XmlResultType v) throws Exception {
      AdaptedResult result = new AdaptedResult();
      result.name = v.name;
      result.content = v.content;
      return result;
    }
  }

  public static final String ELEMENTNAME = "result";

  private List<Object> content;

  private String name;

  public XmlResultType(String name, final String pPath, List<Object> content) {
    this.name=name;
    this.content=content;
    setPath(pPath);
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.IXmlResultType#getContent()
   */
  @Override
  public List<Object> getContent() {
    if (content == null) {
      content = new ArrayList<>();
    }
    return this.content;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.IXmlResultType#getName()
   */
  @Override
  public String getName() {
    return name;
  }

  /* (non-Javadoc)
   * @see nl.adaptivity.process.processModel.IXmlResultType#setName(java.lang.String)
   */
  @Override
  public void setName(final String value) {
    this.name = value;
  }

  public static XmlResultType get(IXmlResultType pImport) {
    if (pImport instanceof XmlResultType) { return (XmlResultType) pImport; }
    XmlResultType result = new XmlResultType(pImport.getName(), pImport.getPath(), null);
    return result;
  }

  /**
   * Transform the given payload as specified by tag.
   * @param pPayload
   * @return
   */
  @Override
  public ProcessData apply(Node pPayload) {
    // TODO add support for variable and function resolvers.
    try {
      // shortcircuit missing path
      Node resultNode = (getPath()==null || ".".equals(getPath())) ? pPayload : (Node) getXPath().evaluate(pPayload, XPathConstants.NODE);
      ProcessData processData = new ProcessData(name, resultNode);
      if (content!=null && content.size()>0) {
        List<Node> result = PETransformer.create(processData).transform(content);
        return new ProcessData(name, result);
      } else {
        return processData;
      }


    } catch (XPathExpressionException e) {
      throw new RuntimeException(e);
    }
  }

}
