/*
 * Copyright (c) 2016.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with Foobar.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.27 at 08:15:55 PM CEST
//


package nl.adaptivity.process.processModel;

import net.devrieze.util.CollectionUtil;
import net.devrieze.util.StringUtil;
import nl.adaptivity.process.processModel.engine.XmlActivity;
import nl.adaptivity.process.processModel.engine.XmlEndNode;
import nl.adaptivity.util.ListFilter;
import nl.adaptivity.xml.schema.annotations.XmlName;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.xml.bind.annotation.XmlAttribute;

import java.util.*;


/**
 * <p>
 * Java class for TProcessModel complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name=&quot;TProcessModel&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *         &lt;element ref=&quot;{http://adaptivity.nl/ProcessEngine/}start&quot;/&gt;
 *         &lt;element ref=&quot;{http://adaptivity.nl/ProcessEngine/}activity&quot;/&gt;
 *         &lt;element ref=&quot;{http://adaptivity.nl/ProcessEngine/}join&quot;/&gt;
 *         &lt;element ref=&quot;{http://adaptivity.nl/ProcessEngine/}end&quot;/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public class XmlProcessModel {

  public XmlProcessModel() {

  }

  public XmlProcessModel(@NotNull final ProcessModel<? extends ProcessNode<?,?>, ? extends ProcessModel<?,?>> m) {
    nodes = (List) filter(CollectionUtil.<Object>copy(m.getModelNodes()), ProcessNode.class);
    name = m.getName();
    owner = m.getOwner()==null ? null : m.getOwner().getName();
    roles = m.getRoles();
    uuid = m.getUuid();
  }

  private List<ProcessNode<?,?>> nodes;

  @Nullable private UUID uuid;

  @XmlAttribute(name = ProcessModelBase.ATTR_NAME)
  private String name;

  @Nullable private String owner;

  private Set<String> roles;

  /**
   * Gets the value of the startOrActivityOrJoin property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the startOrActivityOrJoin property.
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getStartOrActivityOrJoin().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link XmlEndNode }
   * {@link XmlActivity } {@link StartNode } {@link Join }
   */
  public List<? extends ProcessNode<?,?>> getNodes() {
    if (nodes == null) {
      nodes = (List) XmlProcessModel.filter(new ArrayList<>(), ProcessNode.class);
    }
    return this.nodes;
  }

  public void setNodes(@NotNull final List<? extends ProcessNode<?,?>> nodes) {
    this.nodes.clear();
    this.nodes.addAll(nodes);
  }

  @NotNull
  private static <T> List<T> filter(@NotNull final List<?> source, final Class<T> clazz) {
    final ListFilter<T> result = new ListFilter<>(clazz, true);
    result.addAllFiltered(source);
    return result;
  }

  public void setName(final String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  @Nullable
  public String getOwner() {
    return owner;
  }

  public void setOwner(final String owner) {
    this.owner = owner;
  }

  public Set<String> getRoles() {
    if (roles == null) {
      roles = new HashSet<>();
    }
    return roles;
  }

  @Nullable
  @XmlName(ProcessModelBase.ATTR_ROLES)
  public String getRolesString() {
    if ((roles == null) || (roles.size() == 0)) {
      return null;
    }
    return StringUtil.join(",", roles);
  }

  @Nullable
  @XmlName("uuid")
  String getUuidString() {
    return uuid==null ? null : uuid.toString();
  }

  public void setUuidString(@Nullable final String uuid) {
    this.uuid = uuid==null ? null : UUID.fromString(uuid);
  }

  /**
   * Read the roles from a string.
   * @param rolesString A comma separated list of roles.
   */
  public void setRolesString(@Nullable final String rolesString) {
    this.roles = new HashSet<>();
    if ((rolesString == null) || (rolesString.trim().length() == 0)) {
      return;
    }
    int i = 0;
    int j = rolesString.indexOf(',');
    while (j >= 0) {
      this.roles.add(rolesString.substring(i, j));
      i = j + 1;
      j = rolesString.indexOf(',', i);
    }
  }

  @Nullable
  public UUID getUuid() {
    return uuid;
  }

}
