//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.27 at 08:15:55 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = nl.adaptivity.process.ProcessConsts.Engine.NAMESPACE,
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns={
           @javax.xml.bind.annotation.XmlNs(prefix=nl.adaptivity.process.ProcessConsts.Soap.SOAP_ENCODING_PREFIX, namespaceURI=nl.adaptivity.process.ProcessConsts.Soap.SOAP_ENCODING_NS),
           @javax.xml.bind.annotation.XmlNs(prefix=javax.xml.XMLConstants.DEFAULT_NS_PREFIX, namespaceURI=nl.adaptivity.process.ProcessConsts.Engine.NAMESPACE)})

package nl.adaptivity.process.processModel.engine;
