/*
 * Copyright (c) 2018.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with ProcessManager.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.24 at 08:12:58 PM CEST 
//


package org.w3.soapEnvelope;

import nl.adaptivity.xml.schema.annotations.AnyType;
import nl.adaptivity.xml.schema.annotations.Child;
import nl.adaptivity.xml.schema.annotations.Element;
import nl.adaptivity.xml.schema.annotations.XmlName;

import java.net.URI;


/**
 * Fault reporting structure
 * <p>
 * Java class for Fault complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Fault">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2003/05/soap-envelope}faultcode"/>
 *         &lt;element name="Reason" type="{http://www.w3.org/2003/05/soap-envelope}faultreason"/>
 *         &lt;element name="Node" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Detail" type="{http://www.w3.org/2003/05/soap-envelope}detail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Element(name="Fault",
         nsUri = Envelope.NAMESPACE,
         nsPrefix = Envelope.PREFIX,
         children = {
              @Child(name="Code",type=Faultcode.class),
              @Child(name="Reason", type=Faultreason.class),
              @Child(name="Node", type= AnyType.class),
              @Child(name="Role", type=URI.class),
              @Child(name="Detail", type=Detail.class)
         })
public class Fault {

  //required
  @XmlName("Code")
  protected Faultcode code;

  //required
  @XmlName("Reason")
  protected Faultreason reason;

  @XmlName("Node")
  protected URI node;

  @XmlName("Role")
  protected URI role;

  @XmlName("Detail")
  protected Detail detail;

  /**
   * Gets the value of the code property.
   * 
   * @return possible object is {@link Faultcode }
   */
  public Faultcode getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   * 
   * @param value allowed object is {@link Faultcode }
   */
  public void setCode(final Faultcode value) {
    this.code = value;
  }

  /**
   * Gets the value of the reason property.
   * 
   * @return possible object is {@link Faultreason }
   */
  public Faultreason getReason() {
    return reason;
  }

  /**
   * Sets the value of the reason property.
   * 
   * @param value allowed object is {@link Faultreason }
   */
  public void setReason(final Faultreason value) {
    this.reason = value;
  }

  /**
   * Gets the value of the node property.
   * 
   * @return possible object is {@link String }
   */
  public URI getNode() {
    return node;
  }

  /**
   * Sets the value of the node property.
   * 
   * @param value allowed object is {@link String }
   */
  public void setNode(final URI value) {
    this.node = value;
  }

  /**
   * Gets the value of the role property.
   * 
   * @return possible object is {@link String }
   */
  public URI getRole() {
    return role;
  }

  /**
   * Sets the value of the role property.
   * 
   * @param value allowed object is {@link String }
   */
  public void setRole(final URI value) {
    this.role = value;
  }

  /**
   * Gets the value of the detail property.
   * 
   * @return possible object is {@link Detail }
   */
  public Detail getDetail() {
    return detail;
  }

  /**
   * Sets the value of the detail property.
   * 
   * @param value allowed object is {@link Detail }
   */
  public void setDetail(final Detail value) {
    this.detail = value;
  }

}
