/*
 * Copyright (c) 2018.
 *
 * This file is part of ProcessManager.
 *
 * ProcessManager is free software: you can redistribute it and/or modify it under the terms of version 3 of the
 * GNU Lesser General Public License as published by the Free Software Foundation.
 *
 * ProcessManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with ProcessManager.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.15 at 03:25:47 PM BST
//


package nl.adaptivity.process.messaging

import nl.adaptivity.process.ProcessConsts
import nl.adaptivity.process.ProcessConsts.Engine
import nl.adaptivity.process.engine.processModel.NodeInstanceState
import nl.adaptivity.util.multiplatform.Class
import nl.adaptivity.util.xml.SimpleXmlDeserializable
import nl.adaptivity.xml.*


@XmlDeserializer(ActivityResponse.Factory::class)
/**
 *
 *
 * The ActivityResponse type is a class that helps with process aware methods.
 * When returning this class from a method this signifies to the
 * [SoapHelper] that the method is ProcessAware, and wraps an actual
 * return value. The activityResponse is communicated through the header.
 *
 *
 *
 * When used by JAXB, instances will result in the right header that signifies
 * task awareness to the process engine. This allows responding to a SOAP
 * message to not signify task completion.
 *
 *
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * ```
 * <complexType name="ActivityResponseType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="taskState">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <enumeration value="Sent"/>
 *             <enumeration value="Acknowledged"/>
 *             <enumeration value="Taken"/>
 *             <enumeration value="Started"/>
 *             <enumeration value="Complete"/>
 *             <enumeration value="Failed"/>
 *             <enumeration value="Cancelled"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * ```
 *
 *
 * @param T The type of the actual return value returned in the result of the
 * SOAP message.
 */
class ActivityResponse<T: Any?> : XmlSerializable, SimpleXmlDeserializable {

    var _returnValue: T? = null
    /**
     * Get the actual return value.
     *
     * @return The actual return value.
     */
    val returnValue: T get() = _returnValue as T

    var _returnType: Class<T>? = null
    /**
     * Get the embedded return type.
     *
     * @return The embedded return type.
     */
    val returnType: Class<T> get() = _returnType!!

    /**
     * The value of the underlying process node state taskState property.
     */
    var nodeInstanceState: NodeInstanceState? = null

    override val elementName: QName
        get() = ELEMENTNAME

    /**
     * Gets the value of the taskState property.
     *
     * @return the name of the [NodeInstanceState]
     */
    /**
     * Sets the value of the taskState property.
     *
     * @param value the new task state.
     */
    var taskStateString: String
        get() = nodeInstanceState!!.name
        set(value) {
            nodeInstanceState = NodeInstanceState.valueOf(value)
        }

    class Factory : XmlDeserializerFactory<ActivityResponse<*>> {

        override fun deserialize(reader: XmlReader): ActivityResponse<*> {
            return ActivityResponse.deserialize<Any>(reader)
        }
    }

    /** Default constructor for jaxb use  */
    protected constructor() {}

    /**
     * Create a new ActivityResponse.
     *
     * @param nodeInstanceState The state of the task requested.
     * @param returnType The actual return type of the method.
     * @param returnValue The value to return.
     */
    protected constructor(nodeInstanceState: NodeInstanceState, returnType: Class<T>, returnValue: T) {
        this.nodeInstanceState = nodeInstanceState
        _returnType = returnType
        _returnValue = returnValue
    }

    override fun deserializeChild(reader: XmlReader): Boolean {
        return false
    }

    override fun deserializeChildText(elementText: CharSequence): Boolean {
        return false
    }

    override fun deserializeAttribute(attributeNamespace: String?, attributeLocalName: String, attributeValue: String): Boolean {
        when (attributeLocalName.toString()) {
            "taskState" -> {
                taskStateString = attributeValue.toString()
                return true
            }
        }
        return false
    }

    override fun onBeforeDeserializeChildren(reader: XmlReader) {

    }

    override fun serialize(out: XmlWriter) {
        out.smartStartTag(ELEMENTNAME) {
            writeAttribute("taskState", nodeInstanceState?.name)
        }
    }

    companion object {

        const val NAMESPACE = ProcessConsts.Engine.NAMESPACE

        val ELEMENTLOCALNAME = "ActivityResponse"
        val ELEMENTNAME = QName(NAMESPACE, ELEMENTLOCALNAME, Engine.NSPREFIX)

        val ATTRTASKSTATE = "taskState"

        /**
         * Static helper factory for creating a new ActivityResponse.
         *
         * @param nodeInstanceState The state of the task requested.
         * @param returnType The actual return type of the method.
         * @param returnValue The value to return.
         * @return
         */
        fun <V:Any> create(nodeInstanceState: NodeInstanceState,
                       returnType: Class<V>,
                       returnValue: V): ActivityResponse<V> {
            return ActivityResponse(nodeInstanceState, returnType, returnValue)
        }

        fun <T> deserialize(reader: XmlReader): ActivityResponse<T> {
            return ActivityResponse<T>().deserializeHelper(reader)
        }
    }

}
