//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.15 at 03:25:47 PM BST 
//


package nl.adaptivity.process.messaging;

import javax.xml.bind.annotation.*;

import nl.adaptivity.process.exec.Task.TaskState;


/**
 * <p>Java class for ActivityResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivityResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="taskState">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Available"/>
 *             &lt;enumeration value="Taken"/>
 *             &lt;enumeration value="Started"/>
 *             &lt;enumeration value="Complete"/>
 *             &lt;enumeration value="Failed"/>
 *             &lt;enumeration value="Cancelled"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "ActivityResponseType")
@XmlRootElement(name=ActivityResponse.ELEMENTNAME, namespace = "http://adaptivity.nl/ProcessEngine/")
public class ActivityResponse<T>  {

    public static final String ELEMENTNAME = "ActivityResponse";
    public static final String TASKSTATEATTRNAME = "taskState";

    private T aReturnValue;
    private Class<T> aReturnType;
    
    
    @XmlTransient
    private TaskState aTaskState;

    // Default constructor for jaxb use
    protected ActivityResponse() {}
    
    public ActivityResponse(TaskState pTaskState, Class<T> pReturnType, T pReturnValue) {
      aTaskState = pTaskState;
      aReturnType = pReturnType;
      aReturnValue = pReturnValue;
    }

    /**
     * Gets the value of the taskState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlAttribute(name = TASKSTATEATTRNAME)
    public String getTaskState() {
        return aTaskState.name();
    }

    /**
     * Sets the value of the taskState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskState(String value) {
        aTaskState = TaskState.valueOf(value);
    }

    public Class<T> getReturnType() {
      return aReturnType;
    }
    
    public T getReturnValue() {
      return aReturnValue;
    }

}
